### ISSUE TITLE
About modification caller

### ISSUE THREAD

**Issue by weishwu** [vahidAK/NanoMethPhase#18]
I read in your paper that Nanopolish performed the best among the 3 callers you tested. I have a few questions:

1. Nanopolish clusters neighboring CpGs when they are very close to each other. In the outputs I got from Nanopolish, ~15% methylation calls are for a cluster of 2-50 CpGs. Is this a problem? Should I assume these CpGs are less accurate and only use the CpGs that got measured independently? When I asked this under Nanopolish git, they said this limitation was due to the training data they used which was 100% methylated. They recommended me to use **dorado** if I need absolute single-CpG methylation.

2. Megalodon is another caller compatible with NanoMethPhase. However it's deprecated by Nanopore and is replaced by **dorado** (https://github.com/nanoporetech/dorado). Is NanoMethPhase compatible with **dorado** outputs?

3. About deepsignal, the team has developed **deepsignal2** which has better performance in 5mCpG detection of human. Is **deepsignal2** compatible with NanoMethphase?

Thanks.

**Comment by vahidAK** [comment]
Hi @weishwu,

I suggest keeping clustered CpGs. NanoMethPhase splits clustered CpGs to per CpG so it should not be a problem. 

For other methylation callers, as long as the output of your methylation caller is what I have explained at the end of the README file it should be fine for NanoMethPhase. However, because nanomethphase matches the read coordinates from methylcall file to the read coordinates from the bam file, the optimal results will be when the same bam or alignments used for methylation calling are used for NanoMethPhase phasing.

Best,
Vahid

**Comment by assafgrw** [comment]
Hi, 
Regarding mod basecalling, I am afraid that Nanopolish is not compatible with the new ONT chemistry (V14). Do you think that Doardo will do the job?

**Comment by vahidAK** [comment]
It should be able to call methylation for v14. Guppy with the appropriate model can also be used to store methylation in a bam file.

**Comment by weishwu** [comment]
Hi @vahidAK. I've run mod base calling using Dorado. Dorado itself only outputs a BAM file with MM/ML tags. I had to run [modkit extract](https://nanoporetech.github.io/modkit/intro_extract.html) to extract the modification information. The format of the output is like below. It has only one probability score (**mod_qual**) while all the 3 methylation callers compatible with NanoMethPhase have two scores. Is there a way to transform this to make it compatible with NanoMethPhase?

```
read_id	forward_read_position	ref_position	chrom	mod_strand	ref_strand	ref_mod_stranfw_soft_clipped_start	fw_soft_clipped_end	read_length	mod_qual	mod_code	base_qual	ref_kmer	query_kmer	canonical_base	modified_primary_base	inferred
0a0a9f4b-6e9f-4e99-9e9e-c639c35f39c2	557	17158282	chr9	+	-	-	0	794	0.013671875	h	9	CCGAA	TTCGG	C	C	false
0a0a9f4b-6e9f-4e99-9e9e-c639c35f39c2	557	17158282	chr9	+	-	-	0	794	0.017578125	m	9	CCGAA	TTCGG	C	C	false
0a0a9f4b-6e9f-4e99-9e9e-c639c35f39c2	103	17158737	chr9	+	-	-	0	794	0.013671875	h	13	TCGTA	TACGA	C	C	false
```

**Comment by vahidAK** [comment]
Hi @weishwu 
I guess using something like :
```
awk -F'\t' '$11=="m" && $3>=0 {print $4,$3,$6,"NA",$1,"NA",1-$10,$10,"NA",$13}' OFS='\t'
```
you should be able to convert this to a DeepSignal-like format and then use nanomethphase. Alternatively, you should be able to haplotag your bam file and use modkit to extract H1 and H2 methylation frequencies from the bam file.

**Comment by weishwu** [comment]
@vahidAK Thanks! Yes, I went through the alternative way by splitting the bam into h1 and h2, running modkit pileup, and then DSS.
Another question: do you think it makes sense to use only the CpGs covered by at least 5 reads (cov >= 5) for DSS test? That's the cutoff I usually use for Illumina WGBS data. Not sure if it's still a reasonable filter for ONT.

**Comment by vahidAK** [comment]
I suggest not to filter because DSS takes care of this and depth will be factored into the statistical computation. See [here](https://www.bioconductor.org/packages/release/bioc/vignettes/DSS/inst/doc/DSS.html#:~:text=Q%3A%20Do%20I%20need%20to,factored%20into%20the%20statistical%20computation.) for more info.

**Comment by weishwu** [comment]
@vahidAK . Got it. Thanks!

**Comment by weishwu** [comment]
Hi @vahidAK 
Sorry to reopen this. I reformatted the `modkit` output according to what you told me above, and then ran `methyl_call_processor`. After that, `phase` gave me an error.

The top lines of the input to `methyl_call_processor`:
```
chrom	pos	strand	pos_in_strand	readname	read_strand	prob_0	prob_1	called_label	k_mer
chr1	10468	+	NA	8f53107b-f511-4363-8c04-bc3424d54b40	NA	0.994141	0.005859375	NA	CTCGC
chr1	10470	+	NA	8f53107b-f511-4363-8c04-bc3424d54b40	NA	0.998047	0.001953125	NA	CGCGG
chr1	10484	+	NA	8f53107b-f511-4363-8c04-bc3424d54b40	NA	0.990234	0.009765625	NA	CCGGC
chr1	10488	+	NA	8f53107b-f511-4363-8c04-bc3424d54b40	NA	0.994141	0.005859375	NA	CCCGC
```

My command-lines are:
```
# methyl_call_processor
python /usr/share/NanoMethPhase/nanomethphase.py methyl_call_processor --tool_and_callthresh deepsignal:0.6 -mc {input}.reformatted.tsv -t {threads} | sort -k1,1 -k2,2n -k3,3n | bgzip > {output.bedgz}
tabix -p bed {output.bedgz}

# phase
python /usr/share/NanoMethPhase/nanomethphase.py phase --include_indels -b {input.aln} -v {input.vcf} -mc {input.meth} -r {params.genome_fasta} -o {params.out_prefix} -of bam,methylcall,bam2bis -t {threads}
```

The full log file is attached. The tail of the log is:
```
Tagging variants to reads from chr9: 100%|██████████ [ Estimated time left: 00:00 ]
Tagging variants to reads from chrX: 100%|██████████ [ Estimated time left: 00:00 ]
Tagging variants to reads from chrY: 100%|██████████ [ Estimated time left: 00:00 ]
Read Seperation Process Started
Processing reads from chr1:   1%|          | 14900/1292811 [00:14<21:07, 1008.50it/s] 
Traceback (most recent call last):
  File "/usr/share/NanoMethPhase/nanomethphase.py", line 2242, in <module>
    main()
  File "/usr/share/NanoMethPhase/nanomethphase.py", line 2236, in main
    args.func(args)
  File "/usr/share/NanoMethPhase/nanomethphase.py", line 1194, in main_phase
    alignmentwriter(result, outHP22BisSam)
  File "/usr/share/NanoMethPhase/nanomethphase.py", line 411, in alignmentwriter
    out_samRead.set_tags(all_tags)
  File "pysam/libcalignedsegment.pyx", line 2656, in pysam.libcalignedsegment.AlignedSegment.set_tags
  File "pysam/libcalignedsegment.pyx", line 385, in pysam.libcalignedsegment.pack_tags
AttributeError: module 'array' has no attribute 'typecode'
```

The alignment was generated using `dorado aligner` and then coordinate-sorted. Variants were called using `Clair3` and then phased using `Whatshap`.

Below is the first line in the BAM. My guess is that some of the tags cannot be processed by pysam?
```
0a8e9d66-3338-4578-a7ff-fbe08d4e2434	2048	chr1	10001	23	169S15M1D32M1D20M1D11M1D34M1D29M1D30M7I57M1D18M2D5M1D63M12D3M1D13M4D32M1D13M1I18M1I6M1I15M3602S	*	0	0	CCCTAACCCTAACCCTCACCCCTAACCCCTAACCCTAACCCTAACCCTGACCCCTAACCCTAACCCTGACCCTAACCCTAACCCTAACCCTAACCCTCACCCTGACCCTCACCCTGACCCTGACCCTGACCCATAACCCATAACCCTAACCCTAACCCTAACCCTAACCTAACCCTAACCCTAACCTAACCCTAACCCTAACCCTAACCCTAACCCAACCCTAACCCTAACCCTAACCTAACCCTAACCTAACCCTAACCCTAACCCTAACCTAACCCTAACCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCCGACCCTGACCCTAACCCTAACCCTAACCCTAACCCTGACCCTGACCCTAACCCTAACCCCAACCCCAACCCCAACCCCGGCCCAACCCCAACCCTAACCCTAACCCTAACCCCAACCCCAACCCCAACCCCAACCCCAACCCCAACCCCAACCCTAACCCTAAACCCTAACCCTAACCCTAACCCTAACCCCAACCCTAACCCCTAACCCCTAACCCTAACCCTAACCCCTAACCCCTAACCCTAACCCAAATAATCACTCAAAATCATCCTTACACTAAAAATGCTAAACTATACAATTTCTAGAAGAAACAATAGAAGAAAAGCTATGTGCCTTTGGGTTTGGTAATGAATTTTAACAAATGATACAAAAGGTTGACATACACAAAAGAAATGACATTGTGGATTTCTTAATATTTAAAGTTTATACTCTGGAAGACACCTTGTTAAGAGAACAAAAAGACAAGCCACATATTGAAGAAAATATTTGCAAAATACACATCTGAGAAAGAATTTGTCTTCAAAATATATAAAAAAGTATTAAAACTAAACAATAAGTTAAACAGCCCAACTAAAAATGCACACATCTGAACAGACACCTCACCAAAGAAGATCTACAGATGGCAAGTAAAGAAACATCAAAAAGATGCTCAACATACTAGAAAACTGAAAACCACAATGAGATAGCACAGCTGGTCTATATCTCTTAGAACTGCTAAACTCCCTAAAAAATGACAAATTGCTGGAGGAAAAACAAGAACTCTTTTCATTGCCGGTGGAACACAATGTACAAGACCAAAACATGCCACCCCAAAATATAATGGTAGGAAACCAGAATATGCCACCCCAAAATATGTCCCTTTGGCTTAAGAATTATTCCAAGCTGATTATTTTGAAAAAATAAATGCTAACAAAGGAAGTTCTGAAAACAGAGTAGAAGTTACCCTTGTGTAAGGAAAATTTACATCTATAAAGGAAATCCCCATTTAAAAGCTACCTCTCTCTACACCAAGAAGAGAAGGATAACTAAATCACTAAAGAGTCTTTAATAGTGGGATATCTGCCACAACACATTTATACAGATACACAGAATTTTATGGCCAAATGGGTAAATCAAATTCTATTCAAATTAAACAAAATTACTCAGGATGTGGCGTATCCCAGGACAGAATGCATCATGTTGAAAAAGAATTTATGCTACAAATTACTATGGTTTGGATGTGGTTTGTCCCCAAGCCATGTTGAAATTTGACCCCCAATGTGGCAGTGTGGGGCGGTGGGGCCTAGTGGATGGTGTTTGGGTCATGGGGATGGATCCCTCATGAATAGATTAATGTCCTCCATGGGGGTCAGTGGGTACTGCTTCTCATAGGAATGGATTAATTCCTGCAGGAGTAGGTAATTAAAAGAGTCTGGCTTCCTTGGCTTCCCTTTTGCTTTCACTTCTGCTATGTGATCTCTGGTGCACCCCTTGCTCCCCTTCCGCTTTCCACCATGAGGTGAAAAAGACTGAAGCCCCACCAGATGCAACTGCCCAATCTCGGACATTCCAGCTACCAGTATTGTGAGCCAAATGAATCTTTTTCACTTATAAATTACCCAGCCTCAGGTATTCTGTTACAGGAAGCACAAGATGGACTAAGACACAAATGTAGGTAAAAACTCACTGAAGGTGGAGGGAAAATGGTGTTGACCTAAGTCACTTTGAAAATCAATAGAATCTGGAGGCTGAAGGCACATGAACTATACTTCATAATTGGATTACATTTTATAAAGTTATTTCCAACAGAAGCAATTGTGAACAATTGTAAAACCACAGTGTCTGTATCTGGAGTAAAACAATGACTTACATAAGTCGCAGATGGTGGGAACCAGCTTTCTCACTGTTGAAGTGGGAGGTTACAAATTAGCAAGACGAGAAGGCTAGAATGATTCCTGTGATAATAGAGATTGGGAGGATGAAGTCAACGTAAACTTATGCTTAGTTTAATATAGATACACACAGTTCTACATAGAAAACTTTATAATTAGGTGTGTGTAGGTAGGTTAGACACACACATATACTTCCTAGCATTGCTAATGAGGGACAAGATACAATGTGCATTCAGCAGCCAGATGTAAGTTTTCCCACCATTCTGAAAGGAATCAGGCTCTTTGAAGAAATGTCTGATACTAGAACTGGGACAGTATAAATATAGGAGCCAGGATAATCTGGAAGTATCAGAAAGTAAGTACTAAAAAAATTAAAATATATCAAACAAAAATAAAAGCCAATAAAAACAGCTACCGATGGCCAACACAGGAAGGAATTGTGCAACATAATGCTATAGTGTTGAATAATAACTAAAGCTTAAAGTAATTATCTAGGTGTCTGTATTTGTATACCTAGGTGAATAAGCAAATGGAGTTGCATAGAAATCTCCTTTGCAAAAGAATTCCAATAACTGATGTAGACACTCAGGCCATCAAGAAGGTGGAGCCAACTCCTCACTCCGTAAGTGTGGGCTCTGCATAGTGACTTGCTCCAAAAGAACACATGCAGTACGGACAAGGAGGAAAAATAACTTCACAGTGGAGAAATCTGACAAACAGTAGCTCTGCCAAATGATCCAAGTGAACATCAAAGCTGACAGTTCACCTTAGAACATGAAGTGACAATGGGGGACATTCTTTAAAATGCCTGACCAATCCTCCTCAGTGCTATGAAGGTCATCATGAGGTGGAAAGCCTGACACACTGTCACTGCCAGGAAGAGCCTACGTGATGACTACATGTCATGCGGGATCCTGGATGGGATCCTGGGTCAGAGTAAGATAGAACTAAGGGAATCCAAATGAAATATGAACTTTAGTTAATAACAGTCTATCAGTATTGGTTCATTAAGTGTGACAAATTCTGTAAGATAATAATAAGCCATGTGAGACACACTGATTGATAGGAGATGTTAATAACAGAGGAAACTAGGTTGCGGCTACATGGGAAATCTCTGCTTTTTTTTTTTTTTTTTCTGACGATTTCTGTGTAAGTAAAAAGCAGATGTAAAATAAAACTTTATTTAAAACACTTTTTAACACTTCCTTGTTTAATTATTTATACCATGAATTACTAGTAATTGACACTGTTAACTAGTCCTGTTTTTAAAAATAAGAGCATTTATGACACAAAAAATTAAACAGTGCAGACTGATATATAAATCAAAACAAATATTCTTTACACGTTTTCTGTTACAGTAGTAACACATATGTGTAAATTTAAGTATCATATTTTTTTCTTGTGCTATGGTTGTGTCCTAGGTTCATTCTCTAAAATGCTGTTCACCTTAGACCAGGAAAAATATTAACCATACAGACTCTGTTTCCAGTCATAGCTAAATATTTTCAAAAGAGTGACTTTGTAAAAACATGTTCCAATGGCAAATTGATTCATTATGATGGGATCAATTGTACGAGTTCCTGTCTTATTATTTCTTTGCCATGCCTACCTTTTAGCCATAATACAACAGAATCAAATCTGGCCACTGGGAAAAAAAGAAAAAAAAAAGAAAAAAGAAAGGTAGGGTCAGGGAAAAAAAAAGAAAGAATGTGAACAGAACTTATGACCATGATGATTAAATATTTTACCACAATGCTTTCTAAAACAGAAGAGTGTAAAAGGATATTCAAAGTCAATTTCCTCAGCGAGGCTTTGCAGAAAATGAGGAAACTAGAAAAACAAAAATGGCAGGACATTCTATGGGTGATTTTAAATGTTGCTATGTTTTATGGGAAAAAAATACTTTACCTTTTAAAGAATCACAAAGAATTATTGGAAACCCAAACTCTGGAATGTTTCAAATTTAGTTCAGCTTCTATG	''((+8653-8<;?A;5332488<=<=>/-=9:;<:=?A@@<<<<;<<,++++1+;;<=?AD>BAB@11111>@DB?DDEDACECC>AACBD@@??=65555976678;86666778777:98889;/....,***,8;20001;=AF@C@CFA=@ACCD<CDEED:7745;<=B?:;;<@A@;;;78BCEHEICCBFDEBCFSCKA@?A=AAAA>6666<A?8>ACEFHECGEHDDFABD@BEA<===99:?@@ACIBCDCBHDCEA>8:844<>?@BC>>><;@@BCDICB@EEF@BDEEGBDBFGJECFGCSEF@IJECEEE@JIFHJDFA<AD@F@??@=::;;<>10001<>?@BDDLGFFIED@DDCBSICBD=33333455556?ABADFHIA@@A66655;88877;233113-*)()('',.367878?BOSGEGHO8>BDHK@@?A99888?87777=:::99@99888>55545=::999>33323?DDFCEFCDD<9;BEEFEEFEBBACFDEGIGFFB@A@@11111=>B@>>@88555>A:9@@=C<<=:<EEAG@?@>,*6611864=9<>@>B???@;>?>>>?@>>??ACCCBDCB:8778:CDCA@@@AA>>>>>??@?????@??88:111297888977.,,+((/78<AB@@@@AA9++>++BDFHEFDCAA@AB@CDEDFFEDBBCCBAA@?@??EF6320/.--..223?;2223389?@BA?@@@ABBBBB==@??@@?ADDCCD@A?====>ABDFCB33333?9::::D998::<ACMJIFDABBDDCEC@@A?A@9843E>976634112=BDDBBCE?@>??BDIECBABECGEDDBB<<=<;;;99222GIFBA@AAADDCDDABBCCFCAA@@BCEDCA@@@ABA@??@AGEFDKFC<<?EECBCDJSHFHF@?85?FDBFGJHEDFEDEHGFFEFFDFN@?980****)76++++8;<==;764445.---+...=CGGHHMSHKHFBBACCDNEEFEBCDCBDDEFDGGGGEGKED::-)))>FKEEDCEFJGHFFFBCCIHSEFCCDDLDFEFIMEEGG22A@AAADDHEFNIHHEEEESSGD>0000/.-,,-,''(()112226878AGHKGDBD<<GP:8GEFISMJIHIEFDF:54649777789FDFEFEEGFIGSSHLG@=999;@,*,..*'&&'''''((((59>DG99999GA8E98888GFFSKLNIHEGEBB@?7?=@>;;10000244211445??@GGIFSMSSGKLJNKKSJHFHGJKSG@??88999DA?FDGKE;9988:;<7CGHOSHIGIHHEG@89888EGC;730+,<=?FLIIHDFI>=>>CDBAHSSFGFCEELKGLPG222@@???@?;76644;:9.-&&&(%&%%$#$&*))*)+2=BBFGDE==<>GKSMJNSOONDFDFHGCD==6.-++,./211124@BCJMIIMGIMIKGHFFDCCDAA52.--068<778==>@A@DDDDA::;<<SHOS@@?==KLESKJLGHFHLENFSKFSSSKSIEQEAADSCB964-)+'$%%%&9;==FOGJHFHSCGGLGRKKHKLOSSRGIKMGIKNKGKGFMSLF6555656?@?@A@?>@@HJGSSEEIJNOGKIKGGGLNSIFJSKEMGDCCFEIGLF?>::B=<<>=,**)())'''))(((''*--9===AA>?>>>D?>>679980000088=CG@@@?::;<@B64443566;<SJJKPSJKGSGGFHC3KOSHHHNSHLHSSPSSJHGSSSKHSSSSIIJSQSD>A>>>=@@>2A@B@B@AA?AJHIKRSHHHGJJSJSSSNISNFHSJSLSSSKJ?CDIDHHSKPGSI>?>>ASSHIIKSSFFFFJJIJQISSSSFKFGMDCECCLFCCEEISQSMSJISBG89IGOKONSSSIJPHJNHQJLJSF872//--20-'((::<:DCHESHILDHSLD::::AHGSIOJJLISSLHJMHJIQGJHJKSOIGHGKKHHHSISSMJLHIED>@EHACBANM@<=BA8=))((()22201255?CJGHHJHSLJLSNGHSDDCBB42222ESSKSKSKGQISGKSSHISSEKJSKJRSQJSISKIIOHISSSLISJGSMQJEJBAA???===::CCBADCEDDBCBA777778AANGKKHFGDDGISJJSKPHIKLGKJSSKFGSMSSHKOOKIJGDB655555>;;;;GIHSSOQKJISGQIELHGEDHHRJGKLKKNISJSOKSLLSPFSMSJSPSSISF<-,*(()%$$#$')$$$$&&&'',4<>AEKFIEF>GCGB==>?9><=C977788DA:8SSMNIHFJELEEEFGEFMMSISJIFJHKGSJFFQLSISKSLFGSH===<<<B@CSJNLELGGHLDD@?AFHFHGESSGGJFIEEGGSLPKNLQMKSJKMRFSISHQHNKLSSKSPSSHGJIIE;63-7FHONHE2111-DGFSEHKIHSDCFCECORSSSMSSSLJISIISHIGKKSKHIGFDCE7.++,/1899:>DFFDDFSHIJF?@A@BIKJSSLJLMGSMSSJSSSJED889SSSPSSSSLJMRHHFGGSJHSKNSSSGSLISBABAAMSESG>====GECBEBGHBMSNMMAABIEOMGSKOSSLSJSSKKLNHJMLDE0000/1/..//45444459:888777=GEHMGNIGLIEFJKJSSLSSKSNKNSRFSIFJA@AAPCNJDA>===>AESIIEEFJISJEEGSSSJKSFSC>D?CDEHFC????>:--555>?@EB9988<<B>>=4.-,(**489:CEKSGFRSJGJSSKGS@@@FBAFEHSHISSHFB@@ISJSLLOSSLSSNSKSHSSCCGISIJSLSSDDDEMSLSJHHIISNSHSISMKOSMSSSNSKSKSHSSSKSOLSLPOILHSIKLJLGKQPIIJJHKMSIKMSSMGLJPSSGSLHEILIHGSISHNISISFDCEA>('''::KFEGMLSNNNSOJGLEOJEGIGBA(&&&'):DJFSFIFPHEFIGGIISJHMGLSKFHFJPOFOJSSNSSBIEHSHISKSIJLRCECFISFSSHPJSFIS=888==AB?;;<<GFEKLKMIC:4333=>ABBCGSL=:<FSLHSKIESLJKNGH9975:<<<>BC@CHFA<==<???EJFJIFKLKPIIQJKSMJJHSFDFEG888888IFFHKEE=====LIKFSMHHGEGCECHHGHKIMSLSHSHNKSPSMSKJSHSKISSJJISHLGSGIIGIGNSHIMCCDGSSMSHJILSKHNOJPNNSHDCDLSQKSKGCEDEJSNGFFIDECEGFGIHSJSSB??>425;8:?ACECEHBBA7('''';;;;<EJHHLSKSSSHSJSKSIHIHGMED====?ILE?ABB>GEGDIHGH::652CCEDDDFDDFGJIIFLJSLPSMGOH;:,++(&&&(./:;;;;=BQSKHKSSLLMQNKKSJKSHGFESFSGISOHSSLSJIHEHJKORSISJHQILSIGJSSSSSJKLSSSLIH=<<<<=ALEEC<:89:DFSSSJSHMSNJHSKGGSSQFGDFJ<=<<<87889FJJGGPSKSRSEJNISSHIOSLDDHGKS;;;:;?A@BFE>2=@AJGGGELHGKLSOKHSJFJNSINJHGJJGC:99:<GLF9(((((?E;9666@>??SHSKSKNJHDCCEEGGOGMMSISLISHSJSLHSGSJMSJLNJSHOSNSMDDBAEJ><<99;@ACBFDFDISJJOHHMSQSHKHSNSSHKMBAA><===CCFKEREFCCC4444(('&%%%$$$%&&'/21)()()*8'<?8''DIFGSIIGHSNLSH@SSHNIRHLEJGMED31111::98''''(JSGICDDCKGIF=982/.,+33=EGDCBDDAD6/.-+,+)())+,22228?C>D=<<=;AEDMIKSGSLHFSHSPJMGJFIGESSEG?<;8898*)))..../58:9:EMHSHGMILD@??@AC///01////(((-*HGSFJSLMSIHSSGGFGIEKMCDACDCCCDBGFFCGDGFFFEFEGEKIJHECCBCGJFEDEFGSHSJHGFEFHGMGDHGFFGGMGLHHMSNSGHHHPFSFFIHJFSNKIGI@1AACDB?:++++,./<>?D?9KIDFEKECCCED?B=94-++,..<;;66666<;22226:=>?@B((((2;<++++++>==ABB??B	RG:Z:A	MM:Z:C+h?,174,42,186,70,21,45,18,53,9,4,49,36,10,47,3,22,6,27,35,35;C+m?,174,42,186,70,21,45,18,53,9,4,49,36,10,47,3,22,6,27,35,35;	ML:B:C,1,212,4,16,25,3,1,33,1,19,4,3,3,3,19,10,16,2,18,1,254,42,1,239,229,252,0,222,254,1,1,252,1,1,236,244,2,1,237,254	NM:i:49	ms:i:647	AS:i:618	nn:i:0	de:f:0.0649652	tp:A:P	cm:i:20	s1:i:137	s2:i:119	MD:Z:15^C32^T20^C11^C25C8^C29^C33A29A5A17^T5T5T2A3^TA0A0A3^T5T57^CCTAACCCCTAA3^T13^CCCT29T2^C52	rl:i:396
```

[Sample_5663A-1-4243P.guppySup.meth_haplotype.log](https://github.com/vahidAK/NanoMethPhase/files/12841435/Sample_5663A-1-4243P.guppySup.meth_haplotype.log)

**Comment by vahidAK** [comment]
Hi @weishwu ,
Can you run it with ```-of methylcall,bam2bis```, and another time with ```-of methylcall ``` to see if it works? As you mentioned, there might be tags in bam causing this issue.

**Comment by weishwu** [comment]
@vahidAK I reran it with `-of methylcall` and it ran through without issues.
