### ISSUE TITLE
Cannot run nanomethphase.py phase TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by kir1to455** [vahidAK/NanoMethPhase#9]
Hello vahidAK,
I have the same  problem as issue #6.
Here is my command line:
nanomethphase phase --bam /ChrX_Methlybed_hg19/mod_mappings_sort.bam --output /ChrX_Methlybed_hg19/nanomethphase --vcf hg19.chrX.vcf.gz --outformat bam --threads 24 --overwrite

Here is the error:
NanoMethPhase selected output format(s): bam
Tagging SNVs to reads from chrX:   0%|                                                                [ Estimated time left: ? ]
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/GPU3090B/miniconda3/envs/dimelo/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/GPU3090B/miniconda3/envs/dimelo/lib/python3.8/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/home/GPU3090B/miniconda3/envs/dimelo/lib/python3.8/site-packages/nanomethphase/__main__.py", line 116, in get_base_info
    phred= pileupread.alignment.query_qualities[
TypeError: 'NoneType' object is not subscriptable
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/GPU3090B/miniconda3/envs/dimelo/bin/nanomethphase", line 8, in <module>
    sys.exit(main())
  File "/home/GPU3090B/miniconda3/envs/dimelo/lib/python3.8/site-packages/nanomethphase/__main__.py", line 1996, in main
    args.func(args)
  File "/home/GPU3090B/miniconda3/envs/dimelo/lib/python3.8/site-packages/nanomethphase/__main__.py", line 729, in main_phase
    results= p.starmap(get_base_info,
  File "/home/GPU3090B/miniconda3/envs/dimelo/lib/python3.8/multiprocessing/pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/home/GPU3090B/miniconda3/envs/dimelo/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
TypeError: 'NoneType' object is not subscriptable

Could you please advice the possible solutions?
Thank you!

**Comment by vahidAK** [comment]
Hi @kir1to455 ,

It seems you are using the mod bam format? so that might not be compatible. Could you attach some of the reads from your bam here?

Thanks,
Vahid

**Comment by kir1to455** [comment]
Hi @vahidAK ,

I am using the  bam file from mod_mappings format that it didn't have base quality, so it caused this problem?

I also noted that you have asked the question in https://github.com/nanoporetech/megalodon/issues/246.

I want to know whether there is any parameter result of megalodon (format) that supports the input of nanomethphase?

Or I need to change the mapping tools? For example , winnowmap & guppy?

Thank you!
Kirito

**Comment by kir1to455** [comment]
mappings.bam format :
![image](https://user-images.githubusercontent.com/87375686/180156839-fbd9f833-2ad7-44dc-98bf-90dc89ad78fa.png)

**Comment by kir1to455** [comment]
mod_mappings.bam format:
![image](https://user-images.githubusercontent.com/87375686/180157209-6427a2ee-3d5a-40b2-882a-8b6dc26971d4.png)
![image](https://user-images.githubusercontent.com/87375686/180157249-55f2e9b1-d706-427b-bb00-edd8e103650b.png)

**Comment by vahidAK** [comment]
@kir1to455 , It seems that your bam file does not include the base quality column and that is the reason for the error.
